### ISSUE TITLE
Splashscreen Improvements

### ISSUE THREAD

**Issue by HerbFargus** [RetroPie/retropie-splashscreens#11]
this is just some ideas future improvements:
- ~~remove the need for one folder per file as its redundant to have folders~~
- cull the list of outdated and other splashes
- have a secondary repository for installing new game based splashscreens.
- ~~integrate a randomiser~~
- make a new default splashscreen

After thinking about it - I dont even see why we have a splashscreen repository.  The repository will only get larger as time goes on, the current system is overly complicated due to having two separate folders with splashscreens.

In my mind, the most ideal situation would be to 
- remove this repository altogether
- have one default splashscreen we ship with that is part of the main RetroPie-Setup script
- Ammend the current splashscreen module to only pull from the user created splashscreen folder (`/home/pi/RetroPie/splashscreens`) (which includes the selector, randomiser, append, and previewer etc.) 
- Maintain a secondary external repository to absolve the RetroPie project of any potential legal risks, and implement an installer allows a user to install files individually from the external repository which then places the files in the `/home/pi/RetroPie/splashscreens` folder rather than dumping the repository as I doubt most users care to have 50+ MB of splashscreens that they won't ever use, or at least give them the option to either install all of them or install them individually.

**Comment by joolswills** [comment]
I think we should keep the repository - but trim it down a bit - useful to have a few installed by default.

with my additional splashscreen changes, it should be more easy to add additional repositories as it is handled by a single function - which is something we could do in the future.

I don't really want to spend more time on splashscreen stuff as I have other priorities. I think it offers enough functionality for now. Users can easily install their own splashscreens and videos etc

**Comment by HerbFargus** [comment]
much appreciated. I'll close this for now then, and perhaps look at it in the future when there are less pressing matters to attend to

a few notes on possible ideas for a downloader from a github repo: https://gist.github.com/Integralist/9482061
