### ISSUE TITLE
Out of date / copyright splashscreens etc

### ISSUE THREAD

**Issue by joolswills** [RetroPie/retropie-splashscreens#2]
@petrockblog @HerbFargus 

Looking through the splashscreens, some contain graphics from copyrighted games, and some reference out of date Retropie versions. I think these should be removed. Let me know if you are happy with this.

**Comment by joolswills** [comment]
I'm not sure of the actual risk, but as users can easily add their own splashscreens, perhaps we shouldn't open ourselves up for possible copyright violations etc.

**Comment by HerbFargus** [comment]
That doesn't bother me if they're removed. I can host a separate repo outside of retropie for fan art with @taalas for people that still want a place to find them. I know @sur0x also has his randomiser repo with a bunch of fan art as well.

**Comment by petrockblog** [comment]
that **is** ok for me!

**Comment by rodrigosiviero** [comment]
Yeah, I've gathered bunch of splashs from forum/internet, you can check it here, https://github.com/sur0x/retropiesplashscreen also with git lfs we can store up to 1gb in images :P if you guys want to add something just make a pull request

**Comment by joolswills** [comment]
https://github.com/RetroPie/retropie-splashscreens/commit/782e3188b7ca2f02c5656c2f07e53a80a667a3ee
