### ISSUE TITLE
No Splashscreen coming up

### ISSUE THREAD

**Issue by digitalmagicians** [RetroPie/retropie-splashscreens#4]
Hello i setup ultimate raspbian with retropie 3.1, raspbian jessie and Kodi im going through the usual process for video splashscreen but i get nothing, it just load straight into ES. Even the normal splashscreen does not show. is there something im missing. Any help would be greatly appreciated.

**Comment by joolswills** [comment]
This is the wrong place for support (this is just a repository of splashscreens) - please use the retropie forum - http://blog.petrockblock.com/retropie/ - also if using Jessie it is not yet completely supported(it's still a work in progress). On jessie you have to disable booting into desktop from raspi-config for the splash to show.

**Comment by digitalmagicians** [comment]
Ok i saw what was wrong the execute permissions on the aslashscreen files was set to nobody and video file was an .m4v

**Comment by digitalmagicians** [comment]
Thanks sorry for post in wrong place
